import type { ITheme } from "survey-core";

export const modifiedTheme: ITheme = {
  themeName: "default-contrast",
  colorPalette: "light",
  isPanelless: false,
  backgroundImage: "",
  backgroundImageFit: "cover",
  backgroundImageAttachment: "scroll",
  backgroundOpacity: 1,
  cssVariables: {
    "--sjs-layer-1-background-500": "#fff",
    "--sjs-layer-1-background-400": "#E6EFF8",
    "--sjs-layer-1-foreground-100": "#E6EFF8",
    "--sjs-layer-1-foreground-50": "#626E76",
    "--sjs-layer-3-background-500": "#ebebeb",
    "--sjs-layer-3-foreground-100": "#000000",
    "--sjs-layer-3-foreground-50": "#00000099",
    "--sjs-layer-2-background-500": "#19b394",
    "--sjs-layer-2-background-400": "#DCDCDC",
    "--sjs-special-haze":
      "hsl(from var(--sjs-special-background) calc(h - var(--sjs-special-haze-deltaH)) calc(s - var(--sjs-special-haze-deltaS)) calc(l - var(--sjs-special-haze-deltaL)) / calc(1 - var(--sjs-special-haze-deltaAlpha)))",
    "--sjs-border-25": "#585757d3",
    "--sjs-border-10": "#E0E5E9",
    "--sjs-primary-background-500": "#626E76",
    "--sjs-primary-background-10":"#E6EFF8",
    "--sjs-primary-background-400":
      "hsl(from var(--sjs-primary-background-500) calc(h - var(--sjs-primary-background-400-deltaH)) calc(s - var(--sjs-primary-background-400-deltaS)) calc(l - var(--sjs-primary-background-400-deltaL)) / calc(1 - var(--sjs-primary-background-400-deltaAlpha)))",
    "--sjs-primary-foreground-100": "#FFFFFF",
    "--sjs-primary-foreground-25": "#FFFFFF40",
    "--sjs-secondary-background-500": "#FFFFFF",
    "--sjs-secondary-background-25":"#E6EFF8",
    "--sjs-secondary-background-10":
      "hsl(from var(--sjs-secondary-background-500) calc(h - var(--sjs-secondary-background-10-deltaH)) calc(s - var(--sjs-secondary-background-10-deltaS)) calc(l - var(--sjs-secondary-background-10-deltaL)) / calc(1 - var(--sjs-secondary-background-10-deltaAlpha)))",
    "--sjs-secondary-foreground-100": "#FFFFFF",
    "--sjs-secondary-forecolor-25": "#FFFFFF40",
    "--sjs-semantic-red-background-500": "#E50A66",
    "--sjs-semantic-red-background-10": "#E50A661A",
    "--sjs-semantic-red-foreground-100": "#FFFFFF",
    "--sjs-semantic-green-background-500": "#19AAB3",
    "--sjs-semantic-green-background-10": "#19AAB31A",
    "--sjs-semantic-green-foreground-100": "#FFFFFF",
    "--sjs-semantic-blue-background-500": "#4F43D9",
    "--sjs-semantic-blue-background-10": "#4F43D91A",
    "--sjs-semantic-blue-foreground-100": "#FFFFFF",
    "--sjs-semantic-yellow-background-500": "#FF710B",
    "--sjs-semantic-yellow-background-10": "#FF710B1A",
    "--sjs-semantic-yellow-foreground-100": "#FFFFFF",
    "--sjs-semantic-white-background-500": "#FFFFFF",
    "--sjs-code-gray-700": "#A4A4A4",
    "--sjs-code-blue-500": "#1E5AB3",
    "--sjs-code-gray-300": "#1C1C1C",
    "--sjs-code-green-500": "#127D60",
    "--sjs-code-red-500": "#D30739",
    "--sjs-code-purple-500": "#AB228D",
    "--sjs-code-yellow-500": "#CC6001",
    "--sjs-code-gray-500": "#686868",
    "--sjs-special-background": "#E6EFF8",
    "--sjs-layer-1-foreground-75": "#000000",
    "--sjs-layer-3-background-400": "#D7D7D7",
    "--sjs-special-glow":
      "hsl(from var(--sjs-special-background) calc(h - var(--sjs-special-glow-deltaH)) calc(s - var(--sjs-special-glow-deltaS)) calc(l - var(--sjs-special-glow-deltaL)) / calc(1 - var(--sjs-special-glow-deltaAlpha)))",
    "--sjs-special-shadow": "#0000004D",
    "--sjs-layer-3-foreground-75": "#000000",
    "--sjs-layer-2-foreground-100": "#000000",
    "--sjs-layer-2-foreground-75": "#000000",
    "--sjs-layer-2-foreground-50": "#00000099",
    "--sjs-border-25-overlay": "#00000040",
    "--sjs-secondary-background-400":
      "hsl(from var(--sjs-secondary-background-500) calc(h - var(--sjs-secondary-background-400-deltaH)) calc(s - var(--sjs-secondary-background-400-deltaS)) calc(l - var(--sjs-secondary-background-400-deltaL)) / calc(1 - var(--sjs-secondary-background-400-deltaAlpha)))",
    "--sjs-primary-background-400-deltaAlpha": "0",
    "--sjs-primary-background-400-deltaH": "0.28",
    "--sjs-primary-background-400-deltaS": "-10.89",
    "--sjs-primary-background-400-deltaL": "11.18",
    "--sjs-primary-background-10-deltaAlpha": "0.9",
    "--sjs-primary-background-10-deltaH": "0",
    "--sjs-primary-background-10-deltaS": "0",
    "--sjs-primary-background-10-deltaL": "0",
    "--sjs-secondary-background-400-deltaAlpha": "0",
    "--sjs-secondary-background-400-deltaH": "0.28",
    "--sjs-secondary-background-400-deltaS": "-10.89",
    "--sjs-secondary-background-400-deltaL": "11.18",
    "--sjs-secondary-background-25-deltaAlpha": "0.75",
    "--sjs-secondary-background-25-deltaH": "0",
    "--sjs-secondary-background-25-deltaS": "0",
    "--sjs-secondary-background-25-deltaL": "0",
    "--sjs-secondary-background-10-deltaAlpha": "0.9",
    "--sjs-secondary-background-10-deltaH": "0",
    "--sjs-secondary-background-10-deltaS": "0",
    "--sjs-secondary-background-10-deltaL": "0",
    "--sjs-special-haze-deltaAlpha": "0.65",
    "--sjs-special-haze-deltaH": "-2.82",
    "--sjs-special-haze-deltaS": "-33.73",
    "--sjs-special-haze-deltaL": "8.43",
    "--sjs-special-glow-deltaAlpha": "0.9",
    "--sjs-special-glow-deltaH": "-2.43",
    "--sjs-special-glow-deltaS": "-30.25",
    "--sjs-special-glow-deltaL": "73.34",
    "--sjs-editorpanel-backcolor": "#E0E5E9",
    "--sjs-editorpanel-hovercolor": "#f9f3f5ff",
    "--sjs-questionpanel-backcolor": "#E6EFF8",
    "--sjs-questionpanel-hovercolor": "#0E8BDF",
    "--sjs-font-family": "Open Sans",
    "--sjs-font-size": "16px",
    "--sjs-corner-radius": "6px",
    "--sjs-base-unit": "8px",
    "--sjs-font-pagetitle-color": "#475057",
    "--sjs-font-pagedescription-color": "#475057",
    "--sjs-shadow-small": "0px 1px 2px #00000014",
    "--sjs-shadow-medium": "0px 3px 6px #0000001A",
    "--sjs-shadow-large": "0px 8px 16px #0000001F",
    "--sjs-shadow-inner": "inset 0px 1px 2px #00000014",
    "--sjs-shadow-small-reset": "0 0 0 #00000000",
    "--sjs-shadow-inner-reset": "inset 0 0 0 #00000000",
    "--sjs-font-questiondescription-color": "#e63c3cff",
    "--sjs-font-editorfont-color": "#252525",
    "--sjs-font-editorfont-placeholdercolor": "#737373",
    "--sjs-border-default": "#E0E5E9",
    "--sjs-border-light": "#E0E6E9",
    "--sjs-border-inside": "#CFD8DC",
    "--sjs-general-backcolor": "#f3f5f9",
    "--sjs-general-backcolor-dark": "#F8F9FB",
    "--sjs-general-backcolor-dim-light": "#F9FAFC",
    "--sjs-general-backcolor-dim-dark": "#F3F5F9",
    "--sjs-general-backcolor-dim": "#F3F5F9",
    "--sjs-general-forecolor": "#0E8BDF",
    "--sjs-general-forecolor-light": "#737373",
    "--sjs-general-dim-forecolor": "#000000",
    "--sjs-general-dim-forecolor-light": "#737373",
    "--sjs-secondary-backcolor": "#607D8B",
    "--sjs-secondary-backcolor-light": "#607d8b1A",
    "--sjs-secondary-backcolor-semi-light": "#607d8b40",
    "--sjs-secondary-forecolor": "#FFFFFF",
    "--sjs-secondary-forecolor-light": "#ffffff40",
    "--sjs-primary-backcolor": "#2b75c0ff",
    "--sjs-primary-backcolor-dark": "#1565C0",
    "--sjs-primary-backcolor-light": "#E3F2FD",
    "--sjs-primary-forecolor": "#FFFFFF",
    "--sjs-primary-forecolor-light": "#ffffff40",
    "--sjs-special-blue": "#1976D2",
    "--sjs-special-blue-light": "#1976d21A",
    "--sjs-special-blue-forecolor": "#FFFFFF",
    "--sjs-special-green": "#2E7D32",
    "--sjs-special-green-light": "#2e7d321A",
    "--sjs-special-green-forecolor": "#FFFFFF",
    "--sjs-special-yellow": "#FFC107",
    "--sjs-special-yellow-light": "#ffc1071A",
    "--sjs-special-yellow-forecolor": "#000000",
    "--sjs-special-red": "#E53935",
    "--sjs-special-red-light": "#e539351A",
    "--sjs-special-red-forecolor": "#FFFFFF",
    "--sjs-font-questiontitle-color": "#093B5C",
    "--ctr-toolbox-item-icon-color-hovered, ":"#080b0cff",
    "--ctr-property-grid-placeholder-text-title-color":"#000",
    "--ctr-menu-item-text-color":"#093B5C",
    "--ctr-toolbox-item-banner-display":"#093B5C",
    "--ctr-toolbox-item-background-color-hovered":"#E6EFF8",
    "--ctr-toolbox-item-text-color-hovered":"#0E8BDF",
    "--ctr-menu-toolbar-button-text-color":"#626E76",
    "--ctr-button-text-color":"#0E8BDF",
    "--ctr-button-text-color-hovered":"#fff",
    "--ctr-button-background-color-hovered":"#0E8BDF",
    "--ctr-survey-ranking-item-text-color-inactiv":"#093B5C",
    "--ctr-list-item-text-color":"#626E76",
    "--ctr-survey-question-panel-toolbar-item-text-color":"#626E76",
    "--ctr-list-item-background-color-selected-submenu":"#0E8BDF",
    "--ctr-menu-toolbar-button-background-color-hovered":"#E6EFF8",
    "--ctr-list-item-background-color-selected":"#E6EFF8",
    "--ctr-list-item-text-color-selected":"#0E588A",
    "--ctr-list-item-text-color-hovered":"#0E588A",
    "--ctr-checkbox-text-color":"#7E8C96",
    "--ctr-label-text-color":"#7E8C96",
    "--ctr-editor-content-text-color" :"#072C45",
    "--ctr-button-group-item-text-color-selected":"#fff",
    "--ctr-button-group-item-background-color-selected":"#0E8BDF",
    "--ctr-button-group-background-color":"#fff",
    "--ctr-button-group-item-background-color":"#fff",
    "--ctr-button-group-item-text-color":"#7E8C96",
    "--ctr-editor-background-color":"#fff",
    // "--ctr-survey-page-border-width-hovered":"#7E8C96"
    "--ctr-survey-page-border-color-selected":"#000000ff",
    "--ctr-survey-page-border-color-hover":"#74BEF0",
    "--ctr-survey-ranking-item-text-color-inactive":"#7E8C96",
    "--ctr-menu-toolbar-button-icon-color":"#a71cd1ff",
    "--ctr-toolbox-search-text-color":"#000000ff",
    // "--ctr-toolbox-item-background-color-hovered":"#E6EFF8"
  }
};
